### PR TITLE
Fix 'BufferError: Object is not writable.' when decompressing Bytes o…

### PR DESCRIPTION
**Pull request by da-wad**
…bject

### CODE REVIEW

**Comment by navjotk** [comment]
Thanks for the contribution. I don't see anything wrong with the change, except for the CI failure. I've rerun it in the hopes that it is a random one. Let's see.

**Comment by da-wad** [comment]
Not convinced the Azure pipelines check failing is related to my change, as other pull-request builds have the same issue?

**Comment by navjotk** [comment]
You're right. Merging. 

As an aside, can you propose a test that tests for the failure you're fixing with this? I'd love to use this opportunity to make the test suite stronger.

**Comment by da-wad** [comment]
The failure was due to different object types created when decompressing from an object created in memory vs. a Bytes object created reading from disk... not sure unit tests should touch the disk, so will add a test to my next pull request instead :-)

**Pull request merged**
